# Generated by Django 6.0 on 2025-12-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_student_phone_student_experience_student_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('skills', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('pay', models.IntegerField()),
                ('job_type', models.CharField(max_length=100)),
            ],
        ),
    ]
