# Generated by Django 6.0 on 2026-03-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student_company_student_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='badge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='interview_attended',
            field=models.IntegerField(default=0),
        ),
    ]
