# Generated by Django 6.0 on 2026-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_badge_student_interview_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='TechNova Pvt Ltd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('internship', 'Internship'), ('part-time', 'Part-time'), ('remote', 'Remote')], default='full-time', max_length=50),
            preserve_default=False,
        ),
    ]
